# Generated by Django 5.0.4 on 2024-07-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_asso_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
