# Generated by Django 5.0.4 on 2024-07-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_asso_app', '0002_periodecotisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occupe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodecotisation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poste',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reunion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typereunion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
