# Generated by Django 5.0.6 on 2025-03-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_asso_app', '0003_association_is_deleted_compterendu_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunion',
            name='type_reunion',
        ),
    ]
